version: '3'
services:
  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    networks:
      fullstack:

  fullstack-redis:
    image: redis:latest
    container_name: full_redis
    environment:
      - REDIS_HOST={REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_DB=${REDIS_DB}
    ports:
      - 6379:6379
    restart: always
    networks:
      - fullstack


volumes:
  api:
  db:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge